date_column: 'Date'
time_column: 'Time'
date_format: '%m-%d-%Y'
time_format: '%H:%M'
timestamp_format: '%m-%d-%Y %H:%M'
code_column: 'Code'
value_column: 'Value'

event_codes:
  33: 'Regular insulin dose'
  34: 'NPH insulin dose'
  35: 'UltraLente insulin dose'

measurement_codes:
  '33': 'Regular insulin dose'
  '34': 'NPH insulin dose'
  '35': 'UltraLente insulin dose'
  '48': 'Unspecified blood glucose measurement'
  '57': 'Unspecified blood glucose measurement'
  '58': 'Pre-breakfast blood glucose measurement'
  '59': 'Post-breakfast blood glucose measurement'
  '60': 'Pre-lunch blood glucose measurement'
  '61': 'Post-lunch blood glucose measurement'
  '62': 'Pre-supper blood glucose measurement'
  '63': 'Post-supper blood glucose measurement'
  '64': 'Pre-snack blood glucose measurement'
  '65': 'Hypoglycemic symptoms'
  '66': 'Typical meal ingestion'
  '67': 'More-than-usual meal ingestion'
  '68': 'Less-than-usual meal ingestion'
  '69': 'Typical exercise activity'
  '70': 'More-than-usual exercise activity'
  '71': 'Less-than-usual exercise activity'
  '72': 'Unspecified special event'

glucose_measurement_columns:
  - 'Unspecified blood glucose measurement'
  - 'Pre-breakfast blood glucose measurement'
  - 'Post-breakfast blood glucose measurement'
  - 'Pre-lunch blood glucose measurement'
  - 'Post-lunch blood glucose measurement'
  - 'Pre-supper blood glucose measurement'
  - 'Post-supper blood glucose measurement'
  - 'Pre-snack blood glucose measurement'

outcome_threshold: 140

other_codes:
  - 65
  - 66
  - 67
  - 68
  - 69
  - 70
  - 71
  - 72

exclude_features:
  - measurement
  - next_measurement